import type {Metadata} from "next";
import {Lato} from 'next/font/google'
import './globals.css';
import Providers from "@/components/Providers";
import AppBar from "@/components/AppBar";

// google font
const lato = Lato({
    subsets: ['latin'],
    weight: ['100', '300', '400', '700', '900']
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={lato.className}>
        <Providers>
            <AppBar/>
            {children}
        </Providers>
        </body>
        </html>
    );
}
